-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1059
--   at:        2017-09-18 12:56:12 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012

--use master
--drop database sf
--create database sf
use sf;


drop table besucht;
drop table kveranst;
drop table geeignet;
drop table setztvor;
drop table kurs;
drop table referent;
drop table person;
go

CREATE TABLE besucht 
    (
     kveranst_knr INTEGER NOT NULL , 
     kveranst_knrlfnd INTEGER NOT NULL , 
     person_pnr INTEGER NOT NULL , 
     bezahlt DATE 
    )
    ON "default"
GO

ALTER TABLE besucht ADD CONSTRAINT besucht_PK PRIMARY KEY CLUSTERED (person_pnr, kveranst_knrlfnd, kveranst_knr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE geeignet 
    (
     kurs_knr INTEGER NOT NULL , 
     referent_pnr INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE geeignet ADD CONSTRAINT geeignet_PK PRIMARY KEY CLUSTERED (referent_pnr, kurs_knr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE kurs 
    (
     knr INTEGER NOT NULL , 
     bezeichn VARCHAR (64) NOT NULL , 
     tage INTEGER NOT NULL , 
     preis FLOAT (6) NOT NULL 
    )
    ON "default"
GO

ALTER TABLE kurs ADD CONSTRAINT kurs_PK PRIMARY KEY CLUSTERED (knr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE kveranst 
    (
     kurs_knr INTEGER NOT NULL , 
     knrlfnd INTEGER NOT NULL , 
     von DATE NOT NULL , 
     bis DATE NOT NULL , 
     ort VARCHAR (32) NOT NULL , 
     plaetze INTEGER NOT NULL , 
     referent_pnr INTEGER 
    )
    ON "default"
GO

ALTER TABLE kveranst ADD CONSTRAINT kveranst_PK PRIMARY KEY CLUSTERED (knrlfnd, kurs_knr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE person 
    (
     pnr INTEGER NOT NULL , 
     fname VARCHAR (32) NOT NULL , 
     vname VARCHAR (32) NOT NULL , 
     ort VARCHAR (32) NOT NULL , 
     land VARCHAR (32) NOT NULL 
    )
    ON "default"
GO

ALTER TABLE person ADD CONSTRAINT person_PK PRIMARY KEY CLUSTERED (pnr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE referent 
    (
     person_pnr INTEGER NOT NULL , 
     gebdat DATE NOT NULL , 
     seit DATE NOT NULL , 
     titel VARCHAR (32) 
    )
    ON "default"
GO

ALTER TABLE referent ADD CONSTRAINT referent_PK PRIMARY KEY CLUSTERED (person_pnr)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE setztvor 
    (
     kurs_knr INTEGER NOT NULL , 
     kurs_knr1 INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE setztvor ADD CONSTRAINT setztvor_PK PRIMARY KEY CLUSTERED (kurs_knr, kurs_knr1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

ALTER TABLE besucht 
    ADD CONSTRAINT besucht_kveranst_FK FOREIGN KEY 
    ( 
     kveranst_knrlfnd, 
     kveranst_knr
    ) 
    REFERENCES kveranst 
    ( 
     knrlfnd , 
     kurs_knr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE besucht 
    ADD CONSTRAINT besucht_person_FK FOREIGN KEY 
    ( 
     person_pnr
    ) 
    REFERENCES person 
    ( 
     pnr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE geeignet 
    ADD CONSTRAINT geeignet_kurs_FK FOREIGN KEY 
    ( 
     kurs_knr
    ) 
    REFERENCES kurs 
    ( 
     knr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE geeignet 
    ADD CONSTRAINT geeignet_referent_FK FOREIGN KEY 
    ( 
     referent_pnr
    ) 
    REFERENCES referent 
    ( 
     person_pnr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE kveranst 
    ADD CONSTRAINT kveranst_kurs_FK FOREIGN KEY 
    ( 
     kurs_knr
    ) 
    REFERENCES kurs 
    ( 
     knr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE kveranst 
    ADD CONSTRAINT kveranst_referent_FK FOREIGN KEY 
    ( 
     referent_pnr
    ) 
    REFERENCES referent 
    ( 
     person_pnr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE referent 
    ADD CONSTRAINT referent_person_FK FOREIGN KEY 
    ( 
     person_pnr
    ) 
    REFERENCES person 
    ( 
     pnr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE setztvor 
    ADD CONSTRAINT setztvor_kurs_FK FOREIGN KEY 
    ( 
     kurs_knr
    ) 
    REFERENCES kurs 
    ( 
     knr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE setztvor 
    ADD CONSTRAINT setztvor_kurs_FKv1 FOREIGN KEY 
    ( 
     kurs_knr1
    ) 
    REFERENCES kurs 
    ( 
     knr 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO
