version: "3"
services:
  db:
    build: docker-oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
  # sqldeveloper:
  #   image: marcelhuberfoo/sqldeveloper
  #   environment:
  #     - DISPLAY=unix$DISPLAY
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     # - /home/koka/workspace/sql:/data:rw
  #   depends_on:
  #     - db
  #   restart: unless-stopped
